services:
  web:
    build: .
    image: hacktifytechnologies/payflow:1.0
    container_name: payflow
    ports:
      - "8092:80"
    environment:
      DB_HOST: db
      DB_NAME: payflow
      DB_USER: root
      DB_PASS: root
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: payflow-mysql
    restart: always
    environment:
      MYSQL_DATABASE: payflow
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "3307:3306"